### ISSUE TITLE
Problem with building an app with the plugin for Android

### ISSUE THREAD

**Issue by tsonevn** [EddyVerbruggen/nativescript-calendar#22] opened 2017-05-05 06:21 UTC
There is an issue with building a sample app with `nativescript-calendar` plugin. This problem could be reproduced with [nativescript-calendar-demo](https://github.com/EddyVerbruggen/nativescript-calendar-demo) only for Android.

Error:
```
/Users/ntsonev/Desktop/git/ticket1107329/ticket1107329/nativescript-calendar-demo/Calendar/platforms/android/src/main/AndroidManifest.xml:27:9-31 Error:
        Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processF0F1DebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.488 secs
Command /Users/ntsonev/Desktop/git/ticket1107329/ticket1107329/nativescript-calendar-demo/Calendar/platforms/android/gradlew failed with exit code 1
```

**Comment by EddyVerbruggen** [comment] 2017-05-05 10:05
Thanks for letting me know. Was caused by the explicit reference to support-v4 in the gradle file. Fixed in 1.2.2.

**Closed by EddyVerbruggen** 2017-05-05 10:05 UTC
Labels: bug
